#!/usr/bin/python

import sys
import time
import subprocess as sp

BIN_DIR = '/usr/mce/bin/'

class dspError(Exception):
    pass

class dsp:
    X, Y, P = 'X', 'Y', 'P'

    def cmd(self, args):
        cmd = [BIN_DIR + 'dsp_cmd', '-qpx'] + [str(x) for x in args]
        p = sp.Popen(cmd, stdout=sp.PIPE, stderr=sp.STDOUT)
        out, err = p.communicate()
        out = out.strip()
        # Format of dsp_cmd output (when invoked with -qp) is:
        #                                              (write, ok)
        #  ok : Y[0] = 0xa5                            (read, ok)
        #  error : read expects at most 2 arguments    (error)
        words = out.split()
        if len(words)>0 and words[0] != 'ok':
            raise dspError, "dsp_cmd says: '%s'" % out
        if len(words) > 1:
            return int(words[4], 0)

    def read(self, mem, addr, n=0):
        if n == 0:
            return self.cmd(['read', mem, '%#x' % addr])
        return [self.read(mem, addr+i) for i in range(n)]

    def write(self, mem, addr, data):
        if not hasattr(data, '__len__'):
            return self.cmd(['write', mem, '%#x' % addr, '%#x' % data])
        for i in range(len(data)):
            self.write(mem, addr+i, data[i])

def get_bit(data, bit):
    return (data >> bit) & 1

def set_bit(data, bit):
    return data | (1 << bit)

def clear_bit(data, bit):
    if get_bit(data, bit):
        data = data ^ (1 << bit)
    return data

ADDRS = {
    'STATUS': 0,
    'MODE': 1,
    'VERSION': 3,
    }
    
status_bits = [
    ('APPLICATION_RUNNING', 0),
    ('SEND_IO_TO_HOST', 1),
    ('FATAL_ERROR', 2),
    ('FO_WRD_RCV', 3),
    ('HST_NFYD', 9),
    ('CON_DEMAND', 10),
    ('CON_MCE', 11),
    ('PCIDMA_RESTART', 16),
    ('PCIDMA_RESUME', 17),
    ('PCIDMA_RETRY', 18),
    ('QT_FLUSH', 20),
    ('RP_BUFFER_FULL', 21),
    ('FREEZER', 22),
    ('MAIN_LOOP_POLL', 23),
    ]

mode_bits = [
    ( 'MODE_APPLICATION', 0),
    ( 'MODE_MCE', 1),
    ( 'MODE_QT', 2),
    ( 'MODE_RP_BUFFER', 3),
    ]

status_dict = dict(status_bits)
mode_dict = dict(mode_bits)

if __name__ == '__main__':        
    d = dsp()
    
    try:
        vers = d.read("X", ADDRS['VERSION'])
    except dspError, msg:
        print 'Failed to query version.  Error message: '
        print ' ', msg
        sys.exit(1)

    print 'DSP code version = %#x' % vers

    stat = d.read("X", ADDRS['STATUS'])
    print 'STATUS = %#06x' % stat
    for k,b in status_bits:
        print '  %-20s : %i' % (k, get_bit(stat, b))

    if vers < 0x550105 or vers >= 0x560000:
        sys.exit(0)

    mode = d.read('X', ADDRS['MODE'])
    print 'MODE = %#06x' % mode
    for k,b in mode_bits:
        print '  %-20s : %i' % (k, get_bit(mode, b))

    print 'Checking main loop...  ',
    stat = set_bit(stat, status_dict['MAIN_LOOP_POLL'])
    d.write('X', ADDRS['STATUS'], stat)
    time.sleep(.1)
    stat = d.read('X', ADDRS['STATUS'])
    if get_bit(stat, status_dict['MAIN_LOOP_POLL']):
        print 'stalled!'
    else:
        print 'running.'
    
