# Create install rule for a library target

install__$(INSTALL_TARGET): mas_base_install
	install -m u+rw,g+rw,o+r --owner=$(MAS_USER) --group=$(MAS_GROUP) \
		$(@:install__%=%) $(MAS_INSTALL_LIB)
	-rm $(MAS_SYS_LIB)$(@:install__%=%)
	ln -s $(MAS_INSTALL_LIB)$(@:install__%=%) $(MAS_SYS_LIB)
