#!/bin/bash

do=$1

sleep 0.5
case $do in
    1)
  # Freeze the loop
	x=`dsp_cmd -qx read x 0 | sed 's/.*=\ //g'`
	x=$(( $x | 4194304 ))
	dsp_cmd -qx write x 0 $x
	;;
    0)
  # Unfreeze the loop
	x=`dsp_cmd -qx read x 0 | sed 's/.*=\ //g'`
	x=$(( $x & !4194304 & 0xffffff ))
	dsp_cmd -qx write x 0 $x
	;;
    *)
	echo what
esac
sleep 0.5