#!/bin/bash

echo "This script is provided for DAS compatibility!"
echo

if [ $# < 3 ]; then
  echo "the usage is: mcebatchgo cmdrepfilename datafilename batch_file"
  echo ie: mcebatchgo  batchcmereply.txt batchdata.txt  mcebatchandgo.txt 
  echo
  echo this script saves 
  echo batchcmdrep.txt in ${CMDREPDIR}
  echo batchdata.txt in $DATADIR.
  echo It reads mcebatchandgo.tx from $USRCONFIGDIR,
  echo make your own batch file there and use it. 
  echo the default svfileFlag is set to 2 \(0: do not save,
  echo 1: save data and cmd-rep, 2: save data only \). 
  echo Normal commands sent and replies also saved in
  echo $LOGFILEDIR/logcmdxxxx 
  echo please modify the script to set svfileFlag=0 or 1 if you do not
  echo want to save the data and cme-reply, or want to save both
  exit 1
endif  

data_file="${DATADIR}$2"
batch_file="${USRCONFIGDIR}$3"

mce_cmd -C "$data_file" -f '$batch_file"
