#!/bin/csh
#SCUBA2 test SDSU_TIMING BOARD DSP data frame script 
# 10/05/2004
# X. Gao xg@roe.ac.uk

source $DRAMA/drama.csh

if ($#argv <5 ) then
  echo
  echo " OBSOLETE - please use mcerun, which creates a .run file for your data."
  echo
  echo "   'Frame data is meaningless without its associated .run file.'"
  echo

#  echo "the usage is: mceframetest startSeq endSeq  filesvFlag(0,1,2) svFilename card"
#  echo "ie:           mceframetest 1  1000 1   fdata.dat  rc1 "
#  echo
#  echo "if filesvFlag=1, the data will be saved in svFilename"
#  echo "    in $DATADIR."
#  echo "if filesvFlag=2, we don't know what happens, but use it."
  exit 1
endif  

set   startSeq=$argv[1]
set     endSeq=$argv[2]
set     svFlag=$argv[3]
set     svFile=$argv[4]
set     card=$argv[5]
set     procNo=1

ditscmd DASDRAMA PCICMD WRITE X 1 0
if ($status) exit 1
ditscmd DASDRAMA SETUP_SEQUENCE  $procNo $svFlag $DATADIR/$svFile
if ($status) exit 1
ditscmd DASDRAMA SEQUENCE $startSeq $endSeq $card
if ($status) exit 1
