#!/bin/bash

# Note to self: learn perl

if [ "$1" == "" ]; then
    echo "Usage:    mcestatus <filename>"
    exit 1
fi

FOUT=${DATADIR}$1

mcestatus_text >> $FOUT

cmd_err=$?
if [ "$cmd_err" != "0" ]; then
    echo -e "mcestatus script failed with code $cmd_err\n" >&2
    exit $cmd_err
fi
