#!/bin/bash

# Note to self: learn perl

echo "<HEADER>"

mce_cmd -q -f mcestatus.mcebat | \
    while read line; do
        words=( $line )
	if [ "${words[3]}" == "#" ]; then
	    continue
	fi

	case "${words[0]}" in

	Cmd)
	    printf "<%s %s %s>" ${words[3]} ${words[4]} ${words[5]}
	    ;;

	Line)
	    for a in `seq 5 $(( ${#words[@]} - 1 ))`; do
		printf " %08i" ${words[$a]}
	    done
	    printf "\n"
	    ;;

	esac
    done

cmd_err=${PIPESTATUS[0]}
if [ "$cmd_err" != "0" ]; then
    exit $cmd_err
fi

echo "</HEADER>"
