
sub-dirs:
	make -C misc
	make -C log_library
	make -C dsp_library
	make -C mce_library

clean:
	make -C misc        clean
	make -C log_library clean
	make -C dsp_library clean
	make -C mce_library clean



.PHONY: sub-dirs
