# Create install rule for a python script target

install__$(INSTALL_TARGET): mas_base_install
	install -m u+rwx,g+rwxs,o+rx --owner=$(MAS_USER) --group=$(MAS_GROUP) \
		 $(@:install__%=%) $(MAS_INSTALL_PYTHON)
