# Create install rule for an header target

install__$(INSTALL_TARGET): mas_base_install
	cp $(@:install__%=%) $(MAS_INSTALL_INC)
	chown $(MAS_USER) $(MAS_INSTALL_INC)$(@:install__%=%)
	chgrp $(MAS_GROUP) $(MAS_INSTALL_INC)$(@:install__%=%)
	-rm $(MAS_SYS_INC)$(@:install__%=%)
	ln -s $(MAS_INSTALL_INC)$(@:install__%=%) $(MAS_SYS_INC)
