# Create install rule for a binary target

install__$(INSTALL_TARGET): mas_bin_install
	cp $(@:install__%=%) $(MAS_INSTALL_BIN)
	chown $(MAS_USER) $(MAS_INSTALL_BIN)$(@:install__%=%)
	chgrp $(MAS_GROUP) $(MAS_INSTALL_BIN)$(@:install__%=%)
	chmod g+s $(MAS_INSTALL_BIN)$(@:install__%=%)
