# Create install rule for a binary target

install__$(INSTALL_TARGET): mas_bin_install
	install -m u+rwx,g+rwxs,o+rx --owner=$(MAS_USER) --group=$(MAS_GROUP) \
		 $(@:install__%=%) $(MAS_INSTALL_BIN)
