# Put git revision of $(VER_TARGET) into $(REPO_VER)

SUB_VER := $(shell git rev-parse HEAD)
BRANCH_ID := $(shell cat $(BASE)/branch_id.txt)
REPO_VER := \"$(BRANCH_ID)/$(SUB_VER)\"

# this returns the total number of commits to this branch.  It's
# similar in spirit to what we used to do using svnversion
# Returns 0 if tree is exported / unversioned.
INT_VER := $(shell git log --oneline | wc -l)
